### ISSUE TITLE
sign up problem

### ISSUE THREAD

**Issue by shahvrushali22** [Nader27/FurnitureGo#3]
Signing up is not happening. Giving error.

**Comment by Nader27** [comment]
firebase need to get configured

**Comment by shahvrushali22** [comment]
Can you give firebase access?

**Comment by Nader27** [comment]
furniture go project on firebase is closed now, so to get it work you will need to recreate firebase project and configure it with the app to work

**Comment by shahvrushali22** [comment]
Can you give your firebase database structure?
